### PR TITLE
Disable accept/delete controls when the editor is read-only

### PR DESCRIPTION
**Pull request by marijnh**
cc @DaRosenberg

### CODE REVIEW

**Comment by marijnh** [comment]
That'd make it a _lot_ more involved to make sure these adjust when the read-only setting is dynamically modified in an existing editor.

**Comment by marijnh** [comment]
No—there's plenty of use cases where you want to perform programmatic edits to the document without allowing direct manipulation by the user. You can add such a transaction filter yourself, if you want (it's a one-liner), but for most situations you want to handle this at the UI level anyway (i.e. hide the button, rather than having a button that does nothing).

**Comment by marijnh** [comment]
Are you sure you're running the updated code? I tested it the same way, and on my side it works.

**Comment by DaRosenberg** [comment]
Yeah, 100% - I can't make sense of this! 😅

I restarted the `npm run demo` task, force-reloaded the browser... can't think of what else to try?

The read-only part works on the editor, just has no effect on the widget 🤯

image

**Comment by marijnh** [comment]
Well, this is what it looks like for me. 

conflict

Did you confirm that you are running the code you think you're running? Does the editor have the cm-read-only class on its top level element?

**Comment by DaRosenberg** [comment]
Ah never mind, I didn't realize it was serving from `/dist` and that I had to rebuild. 🤦🏻‍♂️ 

It works now, except the text styling disappears in read-only mode - but I think maybe I can fix that one. :)

Thanks!

**Comment by DaRosenberg** [comment]
> It works now, except the text styling disappears in read-only mode - but I think maybe I can fix that one. :)

Nope, that one was my fault too.

**Pull request merged**
